### ISSUE TITLE
Provide values that don't choose labels

### ISSUE THREAD

**Issue by joneshf** [natefaubion/purescript-run#12]
We discussed on slack providing alternates where the label is not already chosen. Opening this issue so it's not lost forever in slack.

The motivation is to have multiple similar effects with different labels. You might want:
```PureScript
foo ::
  forall r.
  Number ->
  URI ->
  Run
    ( "division by zero" :: EXCEPT Int
    , unparsable :: EXCEPT String
    , "number of failures" :: STATE Natural
    , "something else" :: STATE Bar
    | r
    )
    Foo
```

An example would be with `Run.Except`, instead of `liftExcept` deciding to make an `except` label:

https://github.com/natefaubion/purescript-run/blob/7c81e9595f7ad9d357ced441797fec2696e4708e/src/Run/Except.purs#L35-L36

it would take an `SProxy s` and make an `s` label:

```PureScript
liftExcept' ∷ ∀ d e a r s. IsSymbol s ⇒ RowCons s (EXCEPT e) d r ⇒ SProxy s → Except e a → Run r a
liftExcept' = Run.lift
```

And then recover `liftExcept` by partially applying like before:

```PureScript
liftExcept ∷ ∀ e a r. Except e a → Run (except ∷ EXCEPT e | r) a
liftExcept = liftExcept' _except
```

It seems like everything should be that sort of moving and partially applying. Once everything has been setup, you would be able to do this for the example:

```PureScript
foo x uri = do
  -- whole bunch of logic
  throw' (SProxy :: SProxy "division by zero") 31
  -- more logic
```

If that sounds good, I'll open a PR.

**Comment by natefaubion** [comment]
Yes, I'd like to have this. I think maybe an `At` suffix is appropriate, like `getAt`, `throwAt`, `catchAt`, etc?
