### ISSUE TITLE
Upload update to pursuit?

### ISSUE THREAD

**Issue by artemisSystem** [natefaubion/purescript-run#25]
The version on pursuit is still 2.0.0. Would be nice if it was updated so that the latest docs were there, and so that other packages that depend on this one don't have broken links to `Run` documentation

**Comment by natefaubion** [comment]
I believe anyone can upload to pursuit.

**Comment by artemisSystem** [comment]
Uploaded 👍

**Comment by natefaubion** [comment]
Thanks!
